input NewProductInput {
    title: String!
    description: String!
    price: Float!
    sizes: [Int!]
}

input UpdateProductInput {
    title: String
    description: String
    price: Float
    sizes: [Int!]
    deleted: Boolean
    showSale: Boolean
}

input CartOrderInput {
    id: Int!
    size: Int!
    count: Int!
}

input UserInfoInput {
    name: String!
    surname: String!
    lastname: String
    phone: String!
    email: String!
}

input CustomPointInput {
    latitude: Float!
    longitude: Float!
    entrance: String!
    apartment: String!
    description: String
}

input DeliveryInput {
    deliveryType: Int!
    PVZID: String
    customPoint: CustomPointInput
}

input OrderFilterInput {
    orderID: Int
    deliveryType: Int
    orderStatus: String
}
