type Mutation {
    addProduct(product: NewProductInput!): Product
    updateProductPrice(id: Int!, newPrice: Float!): Product
    deleteProduct(id: Int!, recovery: Boolean): Boolean
}
type Query {
    getProducts(id: ID, showDeleted: Boolean): [Product]
    getSizes: [Size]

    register(login: String!, password: String!): Boolean
    login(login: String!, password: String!): Boolean
    logout: Boolean
}
